language: objective-c
osx_image: xcode9
xcode_project: KDInteractiveNavigationController
# xcode_workspace: <WORKSPACE_PLACEHOLDER>
xcode_scheme: KDInteractiveNavigationController
xcode_sdk: iphonesimulator10.0
env:
  global:
    - FRAMEWORK_NAME=KDInteractiveNavigationController
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  # - carthage bootstrap
script:
  - set -o pipefail && xcodebuild test -verbose -scheme "KDInteractiveNavigationController" -destination "platform=iOS Simulator,OS=10.0,name=iPhone 7 Plus" ONLY_ACTIVE_ARCH=NO | xcpretty
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
skip_cleanup: true
on:
  repo: repo/repo
  tags: true
